1

In [2]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn import preprocessing
from sklearn.model_selection import train_test_split

In [3]:
penguins = pd.read_csv('penguins_af.csv',index_col = 'Unnamed: 0')
penguins.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
4  Adelie  Torgersen            36.7           19.3              193.0   
5  Adelie  Torgersen            39.3           20.6              190.0   

   body_mass_g     sex  year  
0       3750.0    male  2007  
1       3800.0  female  2007  
2       3250.0  female  2007  
4       3450.0  female  2007  
5       3650.0    male  2007

In [4]:
y = penguins.pop('species').values
penguins = penguins.drop(columns=['island', 'sex', 'year'])
X = penguins.values
q = [39.5,17.4,186,3800.0]
X[0]

array([  39.1,   18.7,  181. , 3750. ])

In [5]:
scaler = preprocessing.StandardScaler().fit(X)
X_scaled = scaler.transform(X)
q_scaled = scaler.transform([q])
q_scaled

array([[-0.82278787,  0.11958397, -1.06947358, -0.50628618]])

choose an appropriate global distance function

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
data_train, data_test, target_train, target_test = train_test_split(X_scaled, y, 
    test_size=0.3, random_state=1)
print("Training set has %d examples" % data_train.shape[0])
print("Test set has %d examples" % data_test.shape[0])

Training set has 233 examples
Test set has 100 examples


In [8]:
penguins_kNN_1 = KNeighborsClassifier(n_neighbors=1, metric='euclidean') 
penguins_kNN_1.fit(data_train,target_train)
predicted_1 = penguins_kNN_1.predict(data_test)
acc_1 = accuracy_score(target_test, predicted_1)
print("Accuracy=%.3f" % acc_1)

Accuracy=0.960


In [9]:
penguins_kNN_2 = KNeighborsClassifier(n_neighbors=1, metric='manhattan') 
penguins_kNN_2.fit(data_train,target_train)
predicted_2 = penguins_kNN_2.predict(data_test)
acc_2 = accuracy_score(target_test, predicted_2)
print("Accuracy=%.3f" % acc_2)

Accuracy=0.950


In [10]:
penguins_kNN_2 = KNeighborsClassifier(n_neighbors=1, metric='cosine') 
penguins_kNN_2.fit(data_train,target_train)
predicted_2 = penguins_kNN_2.predict(data_test)
acc_2 = accuracy_score(target_test, predicted_2)
print("Accuracy=%.3f" % acc_2)

Accuracy=0.960


Select 'euclidean' to test the global distance and find the closest data label

In [12]:
penguins_kNN = KNeighborsClassifier(n_neighbors=1, metric='euclidean') 
penguins_kNN.fit(X,y)

KNeighborsClassifier(metric='euclidean', n_neighbors=1)

In [13]:
print('Query is classified as',penguins_kNN.predict([q])[0] )

Query is classified as Adelie


In [14]:
penguins_kNN.kneighbors([q])

(array([[0.]]), array([[1]], dtype=int64))

Euclidean distance calculation

In [19]:
from scipy.spatial.distance import euclidean
x1 = [39.1,18.7,181.0,3750.0]
x2 = [50.2,14.3,218,5700]
d1 = euclidean(q, x1)
d2 = euclidean(q, x2) 
print(f"Distance from q to x1 (Adelie): {d1}")
print(f"Distance from q to x2 (Gentoo): {d2}")

Distance from q to x1 (Adelie): 50.26778292306117
Distance from q to x2 (Gentoo): 1900.3021075607953


In [21]:
x1_scaled = scaler.transform([x1])
x2_scaled = scaler.transform([x2])
d1 = euclidean(q_scaled[0], x1_scaled[0]) 
d2 = euclidean(q_scaled[0], x2_scaled[0]) 
print(f"Distance from q to x1 (Adelie): {d1}")
print(f"Distance from q to x2 (Gentoo): {d2}")

Distance from q to x1 (Adelie): 0.7576265548305232
Distance from q to x2 (Gentoo): 4.13985941584515


Manhattan distance calculation

In [24]:
from scipy.spatial.distance import cityblock
d1 = cityblock(q, x1)
d2 = cityblock(q, x2) 
print(f"Distance from q to x1 (Adelie): {d1}")
print(f"Distance from q to x2 (Gentoo): {d2}")

Distance from q to x1 (Adelie): 56.7
Distance from q to x2 (Gentoo): 1945.8


In [26]:
x1_scaled = scaler.transform([x1])
x2_scaled = scaler.transform([x2])
d1 = cityblock(q_scaled[0], x1_scaled[0]) 
d2 = cityblock(q_scaled[0], x2_scaled[0]) 
print(f"Distance from q to x1 (Adelie): {d1}")
print(f"Distance from q to x2 (Gentoo): {d2}")

Distance from q to x1 (Adelie): 1.1538687527644906
Distance from q to x2 (Gentoo): 8.185875131454354


2

a) x1,x3,x5,  2--over  1--under  So Q will be over
b) x1,x3,x5,x7   2--over  2--under 
c) x1 = 1/1.5 = 0.67 ,x3 = 1/1.8 = 0.56 ,x5 = 1/2.2 = 0.45 ,x7 = 1/2.4 = 0.42; Over = 1.22 under = 0.87 So Over

4

In [31]:
house_C_kNN = KNeighborsClassifier(n_neighbors=1, metric='correlation') 
house_C_kNN.fit(X,y)
print('Query is classified as',house_C_kNN.predict([q])[0] )

Query is classified as Adelie


6

In [42]:
from ucimlrepo import fetch_ucirepo 
import time  
# fetch Sepsis dataset 
sepsis_survival_minimal_clinical_records = fetch_ucirepo(id=827) 
  
# data (as pandas dataframes) 
X_raw = sepsis_survival_minimal_clinical_records.data.features 
y = sepsis_survival_minimal_clinical_records.data.targets.values.ravel()
X_raw.shape, y.shape

((110341, 3), (110341,))

In [44]:
X_tr_raw, X_ts_raw, y_train, y_test = train_test_split(X_raw, y, test_size=1/3)

scaler = preprocessing.StandardScaler().fit(X_tr_raw) #A scaler object
X_train = scaler.transform(X_tr_raw)
X_test = scaler.transform(X_ts_raw)
X_train.shape, X_test.shape

((73560, 3), (36781, 3))

scikit-learn provides two strategies to speed up k-NN, ball_tree and kd_tree.Compare the performance of these two algorithms with brute force search brute.

In [55]:
algs = ['brute', 'ball_tree', 'kd_tree']

In [57]:
for alg in algs:
    Sep_kNN = KNeighborsClassifier(n_neighbors=3, algorithm = alg) 
    Sep_kNN.fit(X_train,y_train)
    t_start = time.time()       
    acc = Sep_kNN.score(X_test,y_test)
    t = time.time()-t_start
    print('Time: %5.2f Accuracy: %5.2f, Algorithm: %s' % (t, acc, alg))

Time:  2.93 Accuracy:  0.90, Algorithm: brute
Time:  2.08 Accuracy:  0.89, Algorithm: ball_tree
Time:  1.86 Accuracy:  0.89, Algorithm: kd_tree
